accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import success_view
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home'),

    path('post/', include('post.urls')),

    path('website/', include('accounts.urls')),

    path('website/', include('accounts.about_url')),

    path('success/', success_view, name='success'),

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    
    path('index/', post_index, name='index'),
    path('create/', post_create, name='create'),
    path('<str:slug>/', post_detail, name='detail'),
    path('<str:slug>/update/', post_update, name='update'),
    path('<str:slug>/delete/', post_delete, name='delete'),
]

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home_view(request):
    if request.user.is_authenticated:

        context = {
            'isim' : 'emir',
        }

    else:
        context = {
            'isim' : 'misafir'
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en",
<head>
    <meta charset="UTF-8" name="viewport" content="width = device-width, initial-scale=1 ">
    <title>{% block title %}Django Dersleri{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/style.css'%}">

</head>
<body>

    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}

    {% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{request.GET.q}}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                <li><a href="{% url 'website:about' %}">Hakkımda</a></li>
                <li><a href="{% url 'website:contact' %}">İletişim</a></li>
                {% if request.user.is_authenticated%}
                <li><a href="{% url 'post:create' %}">Yazi Ekle</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else%}
                <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a href="{% url 'accounts:register' %}">Kayit Ol</a></li>
                {% endif %}

                
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{%block title%}Anasayfa{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row" style="margin-bottom: 30px;">
            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px;">1.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px;">2.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(0, 255, 191); height: 100px;">3.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(221, 255, 0); height: 100px;">4.urun</div>
        </div>
        <div class="row" style="margin-bottom: 30px;">
            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px;">1.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px;">2.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(0, 255, 191); height: 100px;">3.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(221, 255, 0); height: 100px;">4.urun</div>
        </div>
        <div class="row" style="margin-bottom: 30px;">
            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px;">1.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px;">2.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(0, 255, 191); height: 100px;">3.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(221, 255, 0); height: 100px;">4.urun</div>
        </div>
         <div class="row" style="margin-bottom: 30px; margin-top: 30px;">
            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px;">1.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px;">2.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(0, 255, 191); height: 100px;">3.urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: rgb(221, 255, 0); height: 100px;">4.urun</div>
        </div>

    </div>


{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> {{ message }}
        </div>
    {% endfor %}
{% endif %}